[#18] change sql db to bolt db
wangkuiyi/ci pull request #19
Opened 2016-12-09 06:54 UTC by helinwang

this PR address issue #18 
package `db` has test coverage of 74.1%, other packages have no coverage yet.
@reyoung @wangkuiyi

2016-12-09 07:42 UTC, wangkuiyi commented on db/db.go
> +	db *bolt.DB
这里是不是可以写成

```
type DB struct {
    *bolt.DB
}
```

这样下面的65处用法都可以简化。比如

```
err := d.db.Update(
```

可以是

```
err := d.Update(
```

2016-12-09 07:42 UTC, wangkuiyi commented on db/db.go
> +		build.ID = buildID
我看这个updater函数里有一连串的 “错误则返回”逻辑：

```
err := DoSomthing()
if err != nil {
    return err
}
```

貌似可以有一种写法，让updater里的很多“如有错误则返回”逻辑的三行代码缩减为一行。

```
func must(e error) {
	if e != nil {
		panic(fmt.Sprint(e))
	}
}

func makeSafeHandlerfn func(*db.Tx) error) func(*db.Tx) error {
	return func(x *db.Tx) (err error) {
		defer func() {
			if r := recover(); r != nil {
				if _, ok := r.(runtime.Error); ok {
					panic(r)
				}
				err = r.(error) // Change the return value.
			}
		}()
		fn()
	}
}

func CreateBuild() {
	err := d.db.Update(makeSafeHandler(func(tx *bolt.Tx) error {
		must(DoA())
		r, e := DoB()
		must(e)
		must(DoC(r))
	}))
}
```

这样一来，所有的

```
if err != nil {
     return err
}
```

就被省掉了。

不过只是一个想法。在这里是否实用应该看节省了多少代码。

上述 `must`函数不用定义，可以用 https://godoc.org/github.com/topicai/candy#Must

另外，上述方法不仅可以用于 `db.Update`，也适用于 `db.View`。

2016-12-09 08:01 UTC, reyoung commented on db/db.go
> +	if start == end {
if start >= end

2016-12-09 09:29 UTC, reyoung requested changes

2016-12-09 09:29 UTC, reyoung commented on builder.go
>  	cmd.Stdout = &stdout
仔细一看，发现了之前改的一个问题。。

Build的stdout和stderr应该是一个channel。然后，哪个通道有数据，那个通道就应该往数据库里面写数据。

因为这两个通道数据出现的时间，对build log非常重要。

如果先写stdout，再写stderr，就把build log错成了两个日志，并且没有记录每一行的时间顺序。

这样很多错误就没办法定位了。

2016-12-09 22:07 UTC, helinwang commented on db/db.go
> +	db *bolt.DB
这里主要是想把`*bolt.DB`这个implementation detail给隐藏起来。如果用embedded struct，这里用`*db.Db`的人就能拿其当作是`*bolt.Db`使用，把实现细节暴露出来了。
比如
```
package main

type a struct {
}

func (a *a) Foo() {
}

type b struct {
	a
}

func main() {
	v := &b{}
	v.Foo() // `a.Foo` exposed through embedded struct, we may want to hide  `a.Foo`
}
```

2016-12-09 22:13 UTC, helinwang commented on db/db.go
> +	if start == end {
`start > end`的error case已经在validate里面处理了。这里主要是非error的start == end，返回空。类似于golang的
```
a := make([]int, 10)
b := b[9:9] // here start == end
c := len(b) == 0 // c is true
```

2016-12-10 00:17 UTC, helinwang commented on db/db.go
> +		build.ID = buildID
嗯我也经常碰到err handling行数太多的问题。一直想不到他别好的解决方法。
我搜了一下，这几篇文章有些帮助：
https://blog.golang.org/errors-are-values
https://blog.golang.org/error-handling-and-go
http://stackoverflow.com/a/18772200/852385
我一开始的观点与最后一个link类似：如果行数不多，直接handle err也挺好。后来看了第一个link，Rob写的文章，很受启发，原来还有这么多写法。
我这里的err check确实很多，对比go语言源代码，
```
if err != nil {
    return err
}
```
这样的代码一个源文件里面出现的次数大概1，2次。与第一个link中提到的一致：
> We recently scanned all the open source projects we could find and discovered that this snippet occurs only once per page or two, less often than some would have you believe. Still, if the perception persists that one must type

看来我这里的err handle实在是太多，应该简化。

简化方法我知道的大致有两种思路，一种是益哥的panic, recover。另一种是改变什么时候检查err这个value。类似于link 1提到的：
```
type errWriter struct {
    w   io.Writer
    err error
}
func (ew *errWriter) write(buf []byte) {
    if ew.err != nil {
        return
    }
    _, ew.err = ew.w.Write(buf)
}
ew := &errWriter{w: fd}
ew.write(p0[a:b])
ew.write(p1[c:d])
ew.write(p2[e:f])
// and so on
if ew.err != nil {
    return ew.err
}
```
我尝试了一下这个思路
```
type tx struct {
	t   *bolt.Tx
	err error
}

type bucket struct {
	b *bolt.Bucket
	t *tx
}

func (b *bucket) Delete(k []byte) {
	if b.t.err != nil {
		return
	}
	b.t.err = b.b.Delete(k)
}

func (t *tx) Bucket(n []byte) *bucket {
	if t.err != nil {
		return nil
	}

	b := t.t.Bucket(n)
	if b == nil {
		return nil
	}
	return &bucket{b: b, t: t}
}

func (t *tx) CreateBucketIfNotExists(n []byte) *bucket {
	b := &bucket{t: t}
	if t.err != nil {
		return b
	}

	bk, err := t.t.CreateBucketIfNotExists(n)
	t.err = err
	if err != nil {
		return b
	}
	b.b = bk
	return b
}

func (b *bucket) Bucket(n []byte) *bucket {
	if b.t.err != nil {
		return nil
	}

	bk := b.b.Bucket(n)
	if bk == nil {
		return nil
	}
	return &bucket{b: bk, t: b.t}
}

func (b *bucket) Cursor() *bolt.Cursor {
	return b.b.Cursor()
}

func (b *bucket) Get(k []byte) []byte {
	return b.b.Get(k)
}

func (b *bucket) CreateBucketIfNotExists(n []byte) *bucket {
	bkt := &bucket{t: b.t}
	if b.t.err != nil {
		return bkt
	}

	bk, err := b.b.CreateBucketIfNotExists(n)
	b.t.err = err
	if err != nil {
		return b
	}
	bkt.b = bk
	return bkt
}

func (b *bucket) NextSequence() uint64 {
	if b.t.err != nil {
		return 0
	}
	n, err := b.b.NextSequence()
	b.t.err = err
	if err != nil {
		return 0
	}
	return n
}

func (b *bucket) Put(k []byte, v []byte) {
	if b.t.err != nil {
		return
	}
	err := b.b.Put(k, v)
	b.t.err = err
}

func dispatch(f func(*tx) error, t *bolt.Tx) error {
	tt := &tx{t: t}
	err := f(tt)
	// need to return tt.err if both tt.err and err are not nil
	if tt.err != nil {
		return tt.err
	}
	return err
}

func (d *DB) update(f func(t *tx) error) error {
	return d.db.Update(func(t *bolt.Tx) error {
		return dispatch(f, t)
	})
}

func (d *DB) view(f func(t *tx) error) error {
	return d.db.View(func(t *bolt.Tx) error {
		return dispatch(f, t)
	})
}
```
以前的
```
err := d.db.Update(func(tx *bolt.Tx) error {
		b, err := tx.CreateBucketIfNotExists(buildBucket)
		if err != nil {
			return err
		}
		buildID, err = b.NextSequence()
		if err != nil {
			return err
		}
		build.ID = buildID
		var buf bytes.Buffer
		enc := gob.NewEncoder(&buf)
		err = enc.Encode(build)
		if err != nil {
			return err
		}
		err = b.Put(itob(buildID), buf.Bytes())
		if err != nil {
			return err
		}

		b, err = tx.CreateBucketIfNotExists(shaBucket)
		if err != nil {
			return err
		}
		b, err = b.CreateBucketIfNotExists([]byte(build.CommitSHA))
		if err != nil {
			return err
		}
		commitID, err := b.NextSequence()
		if err != nil {
			return err
		}
		err = b.Put(itob(commitID), itob(build.ID))
		if err != nil {
			return err
		}

		b, err = tx.CreateBucketIfNotExists(refBucket)
		if err != nil {
			return err
		}
		b, err = b.CreateBucketIfNotExists(itob(uint64(build.T)))
		if err != nil {
			return err
		}
		b, err = b.CreateBucketIfNotExists([]byte(build.Ref))
		if err != nil {
			return err
		}
		refID, err := b.NextSequence()
		if err != nil {
			return err
		}
		err = b.Put(itob(refID), itob(build.ID))
		if err != nil {
			return err
		}

		b, err = tx.CreateBucketIfNotExists(pendingBucket)
		if err != nil {
			return err
		}
		err = b.Put(itob(buildID), make([]byte, 0))
		return err
	})
```
变成了
```
err := d.update(func(tx *tx) error {
		b := tx.CreateBucketIfNotExists(buildBucket)
		buildID = b.NextSequence()
		if tx.err != nil {
			return tx.err
		}

		build.ID = buildID
		var buf bytes.Buffer
		enc := gob.NewEncoder(&buf)
		err := enc.Encode(build)
		if err != nil {
			return err
		}
		b.Put(itob(buildID), buf.Bytes())
		tx.CreateBucketIfNotExists(shaBucket)
		b.CreateBucketIfNotExists([]byte(build.CommitSHA))
		commitID := b.NextSequence()
		b.Put(itob(commitID), itob(build.ID))
		b = tx.CreateBucketIfNotExists(refBucket)
		b = b.CreateBucketIfNotExists(itob(uint64(build.T)))
		b = b.CreateBucketIfNotExists([]byte(build.Ref))
		refID := b.NextSequence()
		b.Put(itob(refID), itob(build.ID))
		b = tx.CreateBucketIfNotExists(pendingBucket)
		b.Put(itob(buildID), make([]byte, 0))
		return nil
	})
```
最后行数改变：
```
2 files changed, 157 insertions(+), 94 deletions(-)
```
效果不是很理想，主要原因是需要重新定义的类型`tx.Tx`, `tx.Bucket`接口太多。
看来还是益哥的建议比较理想。

2016-12-10 01:12 UTC, helinwang commented on db/db.go
> +		build.ID = buildID
Done.

2016-12-10 01:26 UTC, wangkuiyi commented on db/db.go
> +	db *bolt.DB
明白了！

2016-12-10 01:33 UTC, wangkuiyi commented on db/db.go
> +func (t *tx) must(err error) {
must没有用到`tx`，为什么要定义成tx的method，而不是全局函数呢？

2016-12-10 01:33 UTC, wangkuiyi commented on db/db.go
> +				fmt.Println("recover")
这个`fmt.Println`是要删掉的?

2016-12-10 01:33 UTC, wangkuiyi commented on db/db.go
> +				case txErr:
这里为什么需要引入一个新类型`txErr`呢？就用error不好吗？

2016-12-12 05:03 UTC, helinwang commented on db/db.go
> +				case txErr:
引入这个类型是为了只有通过`tx.must(err)`产生的panic才会recover。对比
```
switch e := r.(type) {
case txErr:
    recover()
```
和
```
if _, ok := r.(runtime.Error); ok {
    panic(r)
}
```
前者只有在`txErr`才会panic，后者除了`r.(runtime.Error)`其它都不会panic。虽然即不是`r.(runtime.Error)`，也不是我们err的panic，会很少。但是理论上我觉得前者好一点。

2016-12-12 05:03 UTC, helinwang commented on db/db.go
> +func (t *tx) must(err error) {
嗯对的，我改一下。

2016-12-12 05:19 UTC, helinwang commented on db/db.go
> +func (t *tx) must(err error) {
Done. 我换了个方法，函数调用里`must`成了`tx`以外另一个参数。请益哥看看合不合适。

2016-12-12 05:19 UTC, helinwang commented on db/db.go
> +				fmt.Println("recover")
good catch! Done.

2016-12-12 07:05 UTC, helinwang commented on builder.go
>  	cmd.Stdout = &stdout
有道理！
done.

2016-12-12 21:19 UTC, wangkuiyi commented on db/db.go
> +				case txErr:
I made a mistake when I was pasting my demo code -- my intention was

```
if e := recover(); e != nil {
  if _, ok := r.(error); ok {
    err = e
  } else {
    panic(e)
  }
}
```

With this intention, I think we don't need to define special error types like `txErr`; instead, we can use a pretty general approach -- `candy.Must` and a generally-applicatble `cachePanic` function which caches all panics and converts them into returning errors.

2016-12-12 21:39 UTC, helinwang commented on db/db.go
> +				case txErr:
I ended up using
```
			if r := recover(); r != nil {
				switch e := r.(type) {
				case error:
					err = e
				default:
					err = fmt.Errorf("recovered panic: %v", e)
				}
			}
```
to make sure every panic is handled (according our discussion that ci server should not crash in any case).
Please let me know if you think we should panic if the type of `r` is not `error` :)

2016-12-12 21:40 UTC, wangkuiyi approved these changes

2016-12-13 02:23 UTC, reyoung approved these changes
LGTM

2016-12-13 02:23 UTC, reyoung commented on builder.go
> +			output = append(output, db.OutputLine{T: db.Stdout, Str: s.Text(), Time: time.Now()})
这里有一个潜在的内存问题。。。如果我故意的想stdout和stderr写一堆文件，可能内存会爆。。

不过似乎也没办法。。。即使写到数据库，硬盘也可能满。。就这样吧。

2016-12-13 02:23 UTC, merged

2016-12-13 04:34 UTC, helinwang commented on builder.go
> +			output = append(output, db.OutputLine{T: db.Stdout, Str: s.Text(), Time: time.Now()})
go语言内存使用据我所知，即使物理内存满了也会swap到swapfile里面的，所以应该很难写满。